= Assign content policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-assign-content/master["Build status", link="https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-assign-content/master/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="^2,^2,^2,^2",options="header"]
|===
|onRequest|onResponse|onRequestContent|onResponseContent

|-
|-
|X
|X

|===

== Description

You can use the `assign-content` policy to change or transform the content of the request body or response body.

This policy is compatible with the https://freemarker.apache.org[Freemarker^] template engine, which allows you to apply
complex transformations, such as transforming from XML to JSON and vice versa.

By default, you can access multiple objects from the template context -- request and response bodies, dictionaries, context
attributes and more.

== Configuration

|===
|Property |Required |Description |Type |Default

.^|scope
^.^|X
|The execution scope of the policy.
^.^|scope
^.^|REQUEST

.^|body
^.^|X
|The data to push as request or response body content.
^.^|string
^.^|-

|===

[source, json]
.Sample
----
"policy-assign-content": {
    "scope":"REQUEST",
    "body":"Put your content here"
}
----

== Examples

=== Inject a dictionary value and the application into the request payload

[source, json]
----
{
  "example": "${context.dictionaries['my-dictionary']['my-value']}",
  "application": "${context.attributes['application']}"
}
----

TIP: You can find more information about default attributes in the Expression Language documentation in the *API Publisher Guide*.

=== Incoming request body content

[source, json]
----
{
  "symbol": "EUR"
}
----

=== Policy example to transform from JSON to XML

Input:

[source, xml]
----
<#assign body = request.content?eval >
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webserviceX.NET/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:GetQuote>
         ${body.symbol}
      </web:GetQuote>
   </soapenv:Body>
</soapenv:Envelope>
----

Expected output:

[source, xml]
----
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webserviceX.NET/">
 <soapenv:Header/>
 <soapenv:Body>
 <web:GetQuote>
 EUR
 </web:GetQuote>
 </soapenv:Body>
</soapenv:Envelope>
----

== Errors

=== HTTP status code

|===
|Code |Message

.^| ```500```
| The body content cannot be transformed.

|===
